#pragma once

enum EServerResponse {
    RPL_WELCOME = 1,
    ERR_NONICKNAMEGIVEN = 431,
    ERR_ERRONEUSNICKNAME = 432,
    ERR_NICKNAMEINUSE = 433,
    ERR_NICKCOLLISION = 436,
    ERR_UNAVAILRESOURCE = 437,
    ERR_NEEDMOREPARAMS = 461,
    ERR_ALREADYREGISTERED = 462
};